using MBColumn.Application.DTOs;
using MBColumn.Application.Reports.Models;
using System.Globalization;
using SystemMath = System.Math;

namespace MBColumn.Infrastructure.Reports.Html;

/// <summary>
/// Builds KaTeX formula blocks for EC2 §6.2 shear, mirroring the LaTeX
/// generated by ShearResultViewModel in the WPF results tab.
/// </summary>
internal static class Ec2ShearLatexBuilder
{
    internal static IReadOnlyList<ReportBlock> BuildShearBlocks(ShearResultDto s, string fUnit)
    {
        var blocks = new List<ReportBlock>();

        // ── Status badge ──────────────────────────────────────────────────────
        blocks.Add(new SummaryBoxBlock(
            s.GoverningStatus == Domain.Enums.CapacityStatus.Pass
                ? $"PASS  —  UR = {s.GoverningUtilisation:0.###}"
                : $"FAIL  —  UR = {s.GoverningUtilisation:0.###}",
            s.GoverningStatus.ToString(), s.GoverningUtilisation,
            [
                ("X-direction", $"VEd = {s.VEdXDisplay:F1} {fUnit},  VRd = {s.VRdXDisplay:F1} {fUnit},  UR = {s.UtilisationX:F3}  →  {(s.StatusX == Domain.Enums.CapacityStatus.Pass ? "Pass" : "Fail")}"),
                ("Y-direction", $"VEd = {s.VEdYDisplay:F1} {fUnit},  VRd = {s.VRdYDisplay:F1} {fUnit},  UR = {s.UtilisationY:F3}  →  {(s.StatusY == Domain.Enums.CapacityStatus.Pass ? "Pass" : "Fail")}"),
            ]));

        // ── Step 1: Concrete contribution VRd,c ──────────────────────────────
        blocks.Add(new HeadingBlock("Step 1  —  Concrete shear capacity  VRd,c  (EC2 §6.2.2)", 3));

        blocks.Add(new FormulaBlock(
            "General formula",
            @"V_{Rd,c}=\max\!\left(\left[C_{Rd,c}\,k\,(100\rho_l\,f_{ck})^{1/3}+k_1\sigma_{cp}\right]b_w d,\;(v_{min}+k_1\sigma_{cp})\,b_w d\right)",
            "", ""));

        blocks.Add(new FormulaBlock("X-direction",
            "",
            BuildConcreteSubLatex(s, isX: true, fUnit),
            s.LinksRequiredX
                ? @"\Rightarrow\; \text{⚠ Links required}"
                : @"\Rightarrow\; \checkmark\;\text{Shear reinforcement not required}"));

        blocks.Add(new FormulaBlock("Y-direction",
            "",
            BuildConcreteSubLatex(s, isX: false, fUnit),
            s.LinksRequiredY
                ? @"\Rightarrow\; \text{⚠ Links required}"
                : @"\Rightarrow\; \checkmark\;\text{Shear reinforcement not required}"));

        if (!s.HasLinks)
        {
            // Utilisation using VRd,c only
            blocks.Add(new HeadingBlock("Utilisation  (no links provided)", 3));
            blocks.Add(new FormulaBlock("",
                @"DCR = \frac{|V_{Ed}|}{V_{Rd,c}}",
                BuildStep1UtilSubLatex(s, isX: true,  fUnit),
                BuildStep1UtilSubLatex(s, isX: false, fUnit)));

            return blocks;
        }

        // ── Step 2: Link contribution VRd,s and strut limit VRd,max ──────────
        blocks.Add(new HeadingBlock("Step 2  —  Link contribution  VRd,s / VRd,max  (EC2 §6.2.3)", 3));

        // Steel properties
        blocks.Add(new FormulaBlock("Link steel",
            "",
            $@"s={F(s.LinkSpacingMm,0)}\;\mathrm{{mm}},\quad f_{{ywd}}=\frac{{f_{{yk}}}}{{\gamma_s}}=\frac{{{F(s.FywkMpa,1)}}}{{1.15}}={F(s.FywdMpa,1)}\;\mathrm{{MPa}}",
            ""));

        if (s.IsCircularHoop)
        {
            blocks.Add(new FormulaBlock("Circular hoop area",
                @"A_h=\frac{\pi\,\phi_h^2}{4}",
                $@"A_h=\frac{{\pi({F(SystemMath.Sqrt(4.0*s.LinkAhMm2/SystemMath.PI),1)})^2}}{{4}}={F(s.LinkAhMm2,2)}\;\mathrm{{mm^2}}",
                ""));

            blocks.Add(new FormulaBlock("Circular hoop model  (Orr-Bath)",
                @"V_{Rd,s}=\frac{\pi}{2}\frac{A_h}{s}D'f_{ywd}\cot\theta",
                BuildCircularHoopSubLatex(s, isX: true,  fUnit),
                BuildCircularHoopSubLatex(s, isX: false, fUnit)));
        }
        else
        {
            blocks.Add(new FormulaBlock("Rectangular link model",
                @"V_{Rd,s}=\frac{A_{sw}}{s}\,z\,f_{ywd}\,\cot\theta",
                BuildRectLinkSubLatex(s, isX: true,  fUnit),
                BuildRectLinkSubLatex(s, isX: false, fUnit)));
        }

        // Strut limit
        blocks.Add(new FormulaBlock("Strut crushing limit  VRd,max",
            @"V_{Rd,max}=\frac{\alpha_{cw}\,b_w\,z\,\nu_1\,f_{cd}}{\cot\theta+\tan\theta}",
            BuildVRdMaxSubLatex(s, isX: true,  fUnit),
            BuildVRdMaxSubLatex(s, isX: false, fUnit)));

        // Step 2 utilisation
        if (s.HasDemand)
        {
            blocks.Add(new HeadingBlock("Step 2 utilisation check", 3));
            blocks.Add(new FormulaBlock("X-direction",
                "",
                BuildStep2UtilSubLatex(s, isX: true),
                s.StatusX == Domain.Enums.CapacityStatus.Fail
                    ? @"\text{⚠ Section fails in shear}" : ""));

            blocks.Add(new FormulaBlock("Y-direction",
                "",
                BuildStep2UtilSubLatex(s, isX: false),
                s.StatusY == Domain.Enums.CapacityStatus.Fail
                    ? @"\text{⚠ Section fails in shear}" : ""));
        }

        // ── Minimum Asw/s (§9.2.2(5)) ────────────────────────────────────────
        blocks.Add(new HeadingBlock("Minimum Asw/s  (EC2 §9.2.2(5))", 3));
        blocks.Add(new FormulaBlock("",
            @"\left(\frac{A_{sw}}{s}\right)_{min}=\rho_{w,min}\,b_w=\frac{0.08\sqrt{f_{ck}}}{f_{yk}}\,b_w",
            BuildMinAswSubLatex(s, isX: true),
            BuildMinAswSubLatex(s, isX: false)));

        // ── Final utilisation ─────────────────────────────────────────────────
        if (s.HasDemand || s.IsCircularHoop)
        {
            blocks.Add(new HeadingBlock("Utilisation", 3));
            blocks.Add(new FormulaBlock("",
                @"DCR=\frac{|V_{Ed}|}{V_{Rd}}",
                BuildUtilSubLatex(s, isX: true,  fUnit),
                BuildUtilSubLatex(s, isX: false, fUnit)));
        }

        if (s.AnyStruttingCritical)
            blocks.Add(new NoteBlock(
                "CRITICAL: Strut crushing governs. Increasing shear links will NOT resolve the failure. Increase the section size or fck."));

        return blocks;
    }

    // ── Private formula builders (mirrors ShearResultViewModel) ──────────────

    private static string BuildConcreteSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double bw  = isX ? s.BwXMm    : s.BwYMm;
        double d   = isX ? s.DEffXMm  : s.DEffYMm;
        double k   = isX ? s.KFactorX : s.KFactorY;
        double rho = isX ? s.RhoLX    : s.RhoLY;
        double v   = isX ? s.VRdcXDisplay : s.VRdcYDisplay;
        return $@"k={F(k,3)},\;\rho_l={F(rho,4)},\;b_w={F(bw,0)}\;\mathrm{{mm}},\;d={F(d,0)}\;\mathrm{{mm}}\;\Rightarrow\;V_{{Rd,c}}={F(v,1)}\;\mathrm{{{fUnit}}}";
    }

    private static string BuildCircularHoopSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double cot = isX ? s.CotThetaX : s.CotThetaY;
        double v   = isX ? s.VRdsXDisplay : s.VRdsYDisplay;
        return $@"V_{{Rd,s}}=\tfrac{{\pi}}{{2}}\cdot\tfrac{{{F(s.LinkAhMm2,2)}}}{{{F(s.LinkSpacingMm,0)}}}\cdot{F(s.CircularHoopCentrelineDiameterMm,0)}\cdot{F(s.FywdMpa,1)}\cdot{F(cot,2)}={F(v,1)}\;\mathrm{{{fUnit}}}";
    }

    private static string BuildRectLinkSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double aswS = isX ? s.AswSX    : s.AswSY;
        double z    = isX ? s.ZXMm     : s.ZYMm;
        double cot  = isX ? s.CotThetaX: s.CotThetaY;
        double v    = isX ? s.VRdsXDisplay : s.VRdsYDisplay;
        string dir  = isX ? "x" : "y";
        return $@"\tfrac{{A_{{sw}}}}{{s}}={F(aswS,4)},\;z={F(z,0)}\;\mathrm{{mm}},\;\cot\theta={F(cot,2)}\;\Rightarrow\;V_{{Rd,s,{dir}}}={F(v,1)}\;\mathrm{{{fUnit}}}";
    }

    private static string BuildVRdMaxSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double bw  = isX ? s.BwXMm    : s.BwYMm;
        double z   = isX ? s.ZXMm     : s.ZYMm;
        double cot = isX ? s.CotThetaX: s.CotThetaY;
        double v   = isX ? s.VRdMaxXDisplay : s.VRdMaxYDisplay;
        string dir = isX ? "x" : "y";
        return $@"b_w={F(bw,0)},\;z={F(z,0)},\;f_{{cd}}={F(s.FcdMpa,2)},\;\cot\theta={F(cot,2)}\;\Rightarrow\;V_{{Rd,max,{dir}}}={F(v,1)}\;\mathrm{{{fUnit}}}";
    }

    private static string BuildMinAswSubLatex(ShearResultDto s, bool isX)
    {
        double bw  = isX ? s.BwXMm : s.BwYMm;
        double req = isX ? s.AswSMinRequiredX : s.AswSMinRequiredY;
        double prov= isX ? s.AswSX : s.AswSY;
        string dir = isX ? "x" : "y";
        bool pass  = isX ? s.AswSMinPassX : s.AswSMinPassY;
        return $@"\frac{{A_{{sw}}}}{{s}}_{{min,{dir}}}=\frac{{0.08\sqrt{{{F(s.FckMpa,1)}}}}}{{{F(s.FywkMpa,1)}}}\cdot{F(bw,0)}={F(req,4)}\;\mathrm{{mm^2/mm}},\quad\frac{{A_{{sw}}}}{{s}}_{{prov}}={F(prov,4)}\;\{(pass ? @"\checkmark" : @"\text{✗}")}";
    }

    private static string BuildStep1UtilSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double vEd  = SystemMath.Abs(isX ? s.VEdXDisplay  : s.VEdYDisplay);
        double vRdc = isX ? s.VRdcXDisplay : s.VRdcYDisplay;
        double util = vRdc > 0 ? vEd / vRdc : 0;
        string dir  = isX ? "x" : "y";
        return $@"DCR_{dir}=\frac{{|{F(vEd,1)}|}}{{{F(vRdc,1)}\;\mathrm{{{fUnit}}}}}={F(util,3)}";
    }

    private static string BuildStep2UtilSubLatex(ShearResultDto s, bool isX)
    {
        double vEd  = SystemMath.Abs(isX ? s.VEdXDisplay  : s.VEdYDisplay);
        double vRds = isX ? s.VRdsXDisplay : s.VRdsYDisplay;
        double util = vRds > 0 ? vEd / vRds : 0;
        string dir  = isX ? "x" : "y";
        return $@"\frac{{|V_{{Ed,{dir}}}|}}{{V_{{Rd,s,{dir}}}}}=\frac{{|{F(vEd,1)}|}}{{{F(vRds,1)}}}={F(util,3)}";
    }

    private static string BuildUtilSubLatex(ShearResultDto s, bool isX, string fUnit)
    {
        double vEd  = SystemMath.Abs(isX ? s.VEdXDisplay : s.VEdYDisplay);
        double vRd  = isX ? s.VRdXDisplay : s.VRdYDisplay;
        double util = isX ? s.UtilisationX : s.UtilisationY;
        string dir  = isX ? "x" : "y";
        return $@"DCR_{dir}=\frac{{|{F(vEd,1)}|}}{{{F(vRd,1)}\;\mathrm{{{fUnit}}}}}={F(util,3)}";
    }

    private static string F(double v, int d)
        => v.ToString($"F{d}", CultureInfo.InvariantCulture);
}
